// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, HasMany } from '@utils'
import { Product } from './product.model'


export class Brand extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    name!: string

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    @HasMany(() => Product)
    products!: Product[]


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}