// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo } from '@utils'
import { User } from '@models'

export class ProductSyncLog extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    file_name!: string

    @Field(["fillable","selectable"])
    file_size!: number

    @Field(["fillable","selectable"])
    total_rows!: number

    @Field(["fillable","selectable"])
    total_new_products!: number

    @Field(["fillable","selectable"])
    total_updated_products!: number

    @Field(["fillable","selectable"])
    total_errors!: number

    @Field(["fillable","selectable"])
    status!: string

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    upload_by_id!: number

    @BelongsTo(() => User)
    uploaded_by!: User


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}