// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo } from '@utils'
import { Category, Brand } from '@models'

export class Product extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    code!: string

    @Field(["fillable","searchable","selectable"])
    name!: string

    @Field(["fillable","selectable"])
    stock!: number

    @Field(["fillable","selectable"])
    last_sequence!: number

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    category_id!: number

    @BelongsTo(() => Category)
    category!: Category

    brand_id!: number

    @BelongsTo(() => Brand)
    brand!: Brand


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}