// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo } from '@utils'
import { Product, Location } from '@models'

export class ProductLabel extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","selectable"])
    sequence!: number

    @Field(["fillable","selectable"])
    code!: string

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    product_id!: number
    @BelongsTo(() => Product)
    product!: Product


    location_id!: number
    @BelongsTo(() => Location)
    location!: Location


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}