// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo, HasMany } from '@utils'
import { Opname, OpnameProductLabel, Product } from '@models'

export class OpnameProduct extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    product_code!: string

    @Field(["fillable","searchable","selectable"])
    product_name!: string

    @Field(["fillable","selectable"])
    initial_stock!: number

    @Field(["fillable","selectable"])
    final_stock!: number

    @Field(["fillable","selectable"])
    deviation_stock!: number

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    product_id!: number
    @BelongsTo(() => Product)
    product!: Product

    opname_id!: number
    @BelongsTo(() => Opname)
    opname!: Opname

    @HasMany(() => OpnameProductLabel)
    labels!: OpnameProductLabel[]


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}