// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, HasMany, BelongsTo } from '@utils'
import { OpnameProduct, OpnameProductLabel, User } from '@models'

export class Opname extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    number!: string

    @Field(["fillable","selectable"])
    start_at!: Date

    @Field(["fillable","selectable"])
    end_at!: Date

    @Field(["fillable","searchable","selectable"])
    status!: "OPEN" | "DONE" | "CANCEL"

    @Field(["fillable","selectable"])
    total_product!: number

    @Field(["fillable","selectable"])
    total_stock!: number

    @Field(["fillable","selectable"])
    total_deviation_product!: number

    @Field(["fillable","selectable"])
    total_deviation_stock!: number

    @Field(["fillable","selectable"])
    total_location!: number

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    @HasMany(() => OpnameProduct)
    products!: OpnameProduct[]

    @HasMany(() => OpnameProductLabel)
    labels!: OpnameProductLabel[]

    created_by_id!: number
    @BelongsTo(() => User)
    created_by!: User

    closed_by_id!: number
    @BelongsTo(() => User)
    closed_by!: User


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}