// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo } from '@utils'
import { Opname, Location } from '@models'

export class OpnameLocation extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    location_name!: string

    @Field(["fillable","selectable"])
    total_product!: number

    @Field(["fillable","selectable"])
    total_stock!: number

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    opname_id!: number
    @BelongsTo(() => Opname)
    opname!: Opname

    location_id!: number
    @BelongsTo(() => Location)
    location!: Location


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}