// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field, BelongsTo } from '@utils'
import { Opname, OpnameProduct, Product, ProductLabel, Location } from '@models'

export class OpnameProductLabel extends Model {
    // =====================>
    // ## Field
    // =====================>


    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>
    opname_id!: number
    @BelongsTo(() => Opname)
    opname!: Opname

    opname_product_id!: number
    @BelongsTo(() => OpnameProduct)
    opname_product!: OpnameProduct

    product_id!: number
    @BelongsTo(() => Product)
    product!: Product

    product_label_id!: number
    @BelongsTo(() => ProductLabel)
    product_label!: ProductLabel

    location_id!: number | null
    @BelongsTo(() => Location)
    location!: Location


    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}