// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : iam.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field } from '@utils'


export class Role extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","searchable","selectable"])
    name!: string

    @Field(["fillable","selectable"])
    permissions!: any

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>



    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}