// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : iam.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import { Model, SoftDelete, Field } from '@utils'


export class UserAccessToken extends Model {
    // =====================>
    // ## Field
    // =====================>
    @Field(["fillable","selectable"])
    user_id!: number

    @Field(["fillable","selectable"])
    agent!: string

    @Field(["fillable","selectable","hidden"])
    token!: string

    @Field(["fillable","selectable"])
    permissions!: Record<string,any>

    @Field(["fillable","selectable"])
    last_used_ip!: string

    @Field(["fillable","selectable"])
    last_used_at!: Date

    @Field(["fillable","selectable"])
    expired_at!: Date

    @SoftDelete()
    deleted_at!: Date


    // =========================>
    // ## Relations
    // =========================>



    // =====================>
    // ## Attribute
    // =====================>



    // =====================>
    // ## Hook
    // =====================>

}