// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { ControllerContext } from "elysia"
import { permission } from '@utils'
import { Opname, OpnameLocation, OpnameProduct, OpnameProductLabel } from '@models'
import { OpnameService } from './_services/opname.service'



// ========================================>
// ## Permission of the resource.
// ========================================>
const p = permission.register({
    "300": {
        name: "Opname",
        accesses: {
            "00": "Melihat",
            "01": "Membuat",
            "02": "Mengubah",
            "03": "Menghapus",
        }
    }
})



export class OpnameController {
    // ========================================>
    // ## Display a listing of the resource.
    // ========================================>
    static async index(c: ControllerContext) {
        p.have("300.00").guard(c)

        const { data, total } = await Opname.query().resolve(c)
        
        c.responseData(data, total)
    }


    // =============================================>
    // ## Store a newly created resource.
    // =============================================>
    static async store(c: ControllerContext) {
        p.have("300.01").guard(c)

        let record = {}

        try {
            record = await OpnameService.create(c.user.id)
        } catch (err) {
            c.responseError(err as Error, "Create Opname")
        }

        c.responseSaved(record)
    }

    // ========================================>
    // ## Display the specified resource.
    // ========================================>
    static async show(c: ControllerContext) {
        p.have("300.00").guard(c)

        const record = await Opname.query().expand(["created_by", "closed_by"]).where('id', c.params.id).getFirst()
        
        c.responseSuccess(record)
    }

    // ============================================>
    // ## Update the specified resource.
    // ============================================>
    static async update(c: ControllerContext) {
        p.have("300.02").guard(c)

        let record = {}

        try {
            record = await OpnameService.complete(c.params.id, c.user.id)
        } catch (err) {
            c.responseError(err as Error, "Complete Opname")
        }
        
        c.responseSaved(record)
    }

    // ============================================>
    // ## Cancel the specified resource.
    // ============================================>
    static async cancel(c: ControllerContext) {
        p.have("300.02").guard(c)

        let record = {}

        try {
            record = await OpnameService.cancel(c.params.id, c.user.id)
        } catch (err) {
            c.responseError(err as Error, "Cancel Opname")
        }
        
        c.responseSaved(record)
    }


    // ===============================================>
    // ## Remove the specified resource.
    // ===============================================>
    static async destroy(c: ControllerContext) {
        p.have("300.03").guard(c)

        const record = await Opname.query().findOrNotFound(c.params.id)
        
        try {
            await record.delete()
        } catch (err) {
            c.responseError(err as Error, "Delete Opname")
        }

        c.responseSuccess(record)
    }


    // ===============================================>
    // ## Display a listing of opname labels.
    // ===============================================>
    static async getLabels(c: ControllerContext) {
        const data = await OpnameProductLabel.query().expand(['product_label', 'location']).where('opname_id', c.params.id).get()
        
        c.responseData(data)
    }


    // ===============================================>
    // ## Add product labels to the opname.
    // ===============================================>
    static async addLabels(c: ControllerContext) {
        p.have("300.02").guard(c)

        let records = []

        try {
            records = await OpnameService.addLabels(c.params.id, c.payload as any)
        } catch (err) {
            c.responseError(err as Error, "Add Labels")
        }

        c.responseSuccess(records)
    }

    // ===============================================>
    // ## Display a listing of opname products.
    // ===============================================>
    static async getProducts(c: ControllerContext) {
        const data = await OpnameProduct.query().where('opname_id', c.params.id).get()
        
        c.responseData(data)
    }


    // ===============================================>
    // ## Display a listing of opname locations.
    // ===============================================>
    static async getLocations(c: ControllerContext) {
        const data = await OpnameLocation.query().expand(['location']).where('opname_id', c.params.id).get()
        
        c.responseData(data)
    }
}
