// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("locations", (table) => {
    table.bigIncrements('id').primary()
    table.string("code", 50).unique().notNullable().index()
    table.string("name", 200).notNullable()
    table.timestamps(true, true)
    table.softDelete()
  })


}