// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("opname_product_labels", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("opnames")
    table.foreignIdFor("opname_products")
    table.foreignIdFor("products")
    table.foreignIdFor("product_labels")
    table.foreignIdFor("locations")
    table.timestamps(true, true)
    table.softDelete()
  })


}