// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("opname_locations", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("opnames")
    table.foreignIdFor("locations")
    table.string("location_name", 200)
    table.integer("total_product")
    table.integer("total_stock")
    table.timestamps(true, true)
    table.softDelete()
  })


}