// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("opname_products", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("opnames")
    table.foreignIdFor("products")
    table.string("product_code", 50)
    table.string("product_name", 200)
    table.integer("initial_stock")
    table.integer("final_stock")
    table.integer("deviation_stock")
    table.timestamps(true, true)
    table.softDelete()
  })


}