// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : opname.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("opnames", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("users", "created_by_id")
    table.foreignIdFor("users", "closed_by_id")
    table.string("number", 50).notNullable().index()
    table.date("start_at").notNullable()
    table.date("end_at")
    table.string("status", 10).defaultTo("OPEN").notNullable().index()
    table.timestamps(true, true)
    table.softDelete()
  })


}