// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("product_sync_logs", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("users")
    table.string("file_name", 255).notNullable()
    table.bigInteger("file_size").unsigned().notNullable()
    table.integer("total_rows")
    table.integer("total_new_products")
    table.integer("total_updated_products")
    table.integer("total_errors")
    table.string("status", 50).notNullable().index()
    table.bigInteger("uploaded_by").unsigned().index()
    table.timestamps(true, true)
    table.softDelete()
  })


}