// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { Knex } from "knex"

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable("product_locations", (table) => {
    table.bigIncrements('id').primary()
    table.foreignIdFor("products")
    table.foreignIdFor("locations")
    table.integer("stock")
    table.timestamps(true, true)
    table.softDelete()
  })


}