// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { ControllerContext } from "elysia"
import { permission } from '@utils'
import { Category } from '@models'



// ========================================>
// ## Permission of the resource.
// ========================================>
const p = permission.register({
    "201": {
        name: "Category",
        accesses: {
            "00": "Melihat",
            "01": "Membuat",
            "02": "Mengubah",
            "03": "Menghapus",
        }
    }
})



export class CategoryController {
    // ========================================>
    // ## Display a listing of the resource.
    // ========================================>
    static async index(c: ControllerContext) {
        p.have("201.00").guard(c)

        const { data, total } = await Category.query().resolve(c)
        
        c.responseData(data, total)
    }


    // =============================================>
    // ## Store a newly created resource.
    // =============================================>
    static async store(c: ControllerContext) {
        p.have("201.01").guard(c)

        await c.validation<Category>({
            "name": ["required","string","max:200","min:1","max:200","unique:categories,name"]
        })

        let record = {}

        try {
            record = await (new Category).pump(c.payload)            
        } catch (err) {
            c.responseError(err as Error, "Create Category")
        }

        c.responseSaved(record)
    }


    // ============================================>
    // ## Update the specified resource.
    // ============================================>
    static async update(c: ControllerContext) {
        p.have("201.02").guard(c)

        const record = await Category.query().findOrNotFound(c.params.id)

        await c.validation<Category>({
            "name": ["required","string","max:200","min:1","max:200","unique:categories,name"]
        })

        try {
            await record.pump(c.payload)
        } catch (err) {
            c.responseError(err as Error, "Update Category")
        }
        
        c.responseSaved(record)
    }


    // ===============================================>
    // ## Remove the specified resource.
    // ===============================================>
    static async destroy(c: ControllerContext) {
        p.have("201.03").guard(c)

        const record = await Category.query().findOrNotFound(c.params.id)
        
        try {
            await record.delete()
        } catch (err) {
            c.responseError(err as Error, "Delete Category")
        }

        c.responseSuccess(record)
    }
}
