// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { ControllerContext } from "elysia"
import { conversion, permission } from '@utils'
import { Location } from '@models'



// ========================================>
// ## Permission of the resource.
// ========================================>
const p = permission.register({
    "203": {
        name: "Location",
        accesses: {
            "00": "Melihat",
            "01": "Membuat",
            "02": "Mengubah",
            "03": "Menghapus",
        }
    }
})



export class LocationController {
    // ========================================>
    // ## Display a listing of the resource.
    // ========================================>
    static async index(c: ControllerContext) {
        p.have("203.00").guard(c)

        const { data, total } = await Location.query().resolve(c)
        
        c.responseData(data, total)
    }


    // =============================================>
    // ## Store a newly created resource.
    // =============================================>
    static async store(c: ControllerContext) {
        p.have("203.01").guard(c)

        c.validation<Location>({
            "name": ["required","string","max:200","min:1","max:200"]
        })

        let record = {}

        try {
            record = await (new Location).pump({
                ...c.payload,
                code: "SOHSL/" + String(conversion.strSlug(c.payload.name, "")).toUpperCase() 
            })            
        } catch (err) {
            c.responseError(err as Error, "Create Location")
        }

        c.responseSaved(record)
    }


    // ============================================>
    // ## Update the specified resource.
    // ============================================>
    static async update(c: ControllerContext) {
        p.have("203.02").guard(c)

        const record = await Location.query().findOrNotFound(c.params.id)

        c.validation<Location>({
            "name": ["required","string","max:200","min:1","max:200"]
        })

        try {
            await record.pump(c.payload)
        } catch (err) {
            c.responseError(err as Error, "Update Location")
        }
        
        c.responseSaved(record)
    }


    // ===============================================>
    // ## Remove the specified resource.
    // ===============================================>
    static async destroy(c: ControllerContext) {
        p.have("203.03").guard(c)

        const record = await Location.query().findOrNotFound(c.params.id)
        
        try {
            await record.delete()
        } catch (err) {
            c.responseError(err as Error, "Delete Location")
        }

        c.responseSuccess(record)
    }
}
