// ============================================
// ## file THIS FILE IS AUTO-GENERATED BY BLUEPRINT
// ?? Blueprint : inventory.blueprint.json
// !! If this comment is removed, blueprint engine WILL NOT override this file.
// ============================================



import type { ControllerContext } from "elysia"
import { permission } from '@utils'
import { Product, ProductLabel } from '@models'
import { ProductService } from './_services/product.service'
import { ProductLabelService } from "./_services/product-label.service"




// ========================================>
// ## Permission of the resource.
// ========================================>
const p = permission.register({
    "200": {
        name: "Product",
        accesses: {
            "00": "Melihat",
            "01": "Membuat",
            "02": "Mengubah",
            "03": "Menghapus",
        }
    }
})



export class ProductController {
    // ========================================>
    // ## Display a listing of the resource.
    // ========================================>
    static async index(c: ControllerContext) {
        p.have("200.00").guard(c)

        const { data, total } = await Product.query().resolve(c)
        
        c.responseData(data, total)
    }


    // =============================================>
    // ## Store a newly created resource.
    // =============================================>
    static async store(c: ControllerContext) {
        p.have("200.01").guard(c)

        await c.validation<Product>({
            "code"   :  ["required","string","max:50","unique:products,code"],
            "name"   :  ["required","string","max:200"],
            "stock"  :  ["numeric"]
        })

        let record = {}

        try {
            record = await (new Product).pump(c.payload)            
        } catch (err) {
            c.responseError(err as Error, "Create Product")
        }

        c.responseSaved(record)
    }


    // ============================================>
    // ## Update the specified resource.
    // ============================================>
    static async update(c: ControllerContext) {
        p.have("200.02").guard(c)

        const record = await Product.query().findOrNotFound(c.params.id)

        await c.validation<Product>({
            "code"   :  ["required","string","max:50","unique:products,code"],
            "name"   :  ["required","string","max:200"],
            "stock"  :  ["numeric"],
        })

        try {
            await record.pump(c.payload)
        } catch (err) {
            c.responseError(err as Error, "Update Product")
        }
        
        c.responseSaved(record)
    }


    // ===============================================>
    // ## Remove the specified resource.
    // ===============================================>
    static async destroy(c: ControllerContext) {
        p.have("200.03").guard(c)

        const record = await Product.query().findOrNotFound(c.params.id)
        
        try {
            await record.delete()
        } catch (err) {
            c.responseError(err as Error, "Delete Product")
        }

        c.responseSuccess(record)
    }


    // =============================================>
    // ## Synchronize products from external source.
    // =============================================>
    static async sync(c: ControllerContext) {
        // p.have("200.04").guard(c)

        const payload = Array.isArray(c.payload) ? c.payload : [c.payload]
        let result = []

        try {
            result = await ProductService.sync(payload)
        } catch (err) {
            c.responseError(err as Error, "Sync Product")
        }

        c.responseSuccess(result, "Products synchronized successfully")
    }


    // =============================================>
    // ## Generate product labels.
    // =============================================>
    static async generateLabels(c: ControllerContext) {
        // p.have("200.05").guard(c)

        const payload = Array.isArray(c.payload) ? c.payload : [c.payload]
        let result: any[] = []

        try {
            result = await ProductLabelService.generate(payload)
        } catch (err) {
            c.responseError(err as Error, "Generate Product Labels")
        }

        c.responseSuccess(result, "Product labels generated successfully")
    }


    // =============================================>
    // ## Display a listing of product labels.
    // =============================================>
    static async getLabels(c: ControllerContext) {
        p.have("200.00").guard(c)

        const { data, total } = await ProductLabel.query().resolve(c)
        
        c.responseData(data, total)
    }
}
